config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :reserves
  get '/reserves/exit/:id', :to=>'reserves#exit', :as => :exit_reserve
  get '/reserves/reservePdf/:id', :to=>'reserves#reservePdf', :as => :pdf_reserve

  resources :vehicles
  resources :slots
  resources :vehicle_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :vehicle_type
  validates :number, uniqueness: true
  validates :number, :vehicle_type_id, presence: true

end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :set_slot, only: [:show, :edit, :update, :destroy]

  # GET /slots
  # GET /slots.json
  def index
    @slots = Slot.all
  end

  # GET /slots/1
  # GET /slots/1.json
  def show
  end

  # GET /slots/new
  def new
    @slot = Slot.new
  end

  # GET /slots/1/edit
  def edit
  end

  # POST /slots
  # POST /slots.json
  def create
    @slot = Slot.new(slot_params)

    respond_to do |format|
      if @slot.save
        format.html { redirect_to @slot, notice: 'Slot was successfully created.' }
        format.json { render :show, status: :created, location: @slot }
      else
        format.html { render :new }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slots/1
  # PATCH/PUT /slots/1.json
  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @slot }
      else
        format.html { render :edit }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1
  # DELETE /slots/1.json
  def destroy
    @slot.destroy
    respond_to do |format|
      format.html { redirect_to slots_url, notice: 'Slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot
      @slot = Slot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slot_params
      params.require(:slot).permit(:number, :vehicle_type_id)
    end
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/slots/_form.html.erb
<%= form_for(slot) do |f| %>
  <% if slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
      <% slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="col-md-12">
          <div class="form-group label-floating">
              <label class="control-label">Nombre o número del espacio</label>
              <%= f.text_field :number, :class => "form-control"%>
          </div>
      </div>
  </div>
  <div class="row">
      <div class="col-md-12">
          <div class="form-group label-floating">
              <label class="control-label">Tipo de Vehículo</label>
              <%= f.select :vehicle_type_id, options_for_select(VehicleType.all.collect { |vehicle_type| [vehicle_type.name, vehicle_type.id] }, @slot.vehicle_type_id), {}, :class => "form-control", :style =>"width: 100%" %>
          </div>
      </div>
  </div>


  <%= f.submit "Crear Espacio",:class => "btn btn-primary pull-right" %>
  <div class="clearfix"></div>
<% end %>

app/views/slots/edit.html.erb
<div class="col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="purple">
            <h4 class="title">Editar Espacio</h4>
        </div>
        <div class="card-content">
        	<%= render 'form', slot: @slot %>
        </div>
    </div>
</div>

<%= link_to 'Ver', @slot %> |
<%= link_to 'Volver', slots_path %>

app/views/slots/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-12">
  <div class="card">
      <div class="card-header" data-background-color="purple">
          <h4 class="title">Espacio</h4>
          <p class="category">Tabla con todos los espacios del estacionamiento</p>
      </div>
      <div class="card-content table-responsive">
          <table class="table">
              <thead class="text-primary">
                  <th>Número de Slot</th>
                  <th>Tipo de Vehículo</th>
                  <th></th>
              </thead>
              <tbody>
                  <% @slots.each do |slot| %>
                    <tr>
                      <td><%= slot.number %></td>
                      <td><%= slot.vehicle_type.name %></td>
                      <td><%= link_to 'Ver', slot %> |
                      <%= link_to 'Editar', edit_slot_path(slot) %> |
                      <%= link_to 'Eliminar', slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
              </tbody>
          </table>
      </div>
  </div>
  
  <%= link_to 'Nuevo Espacio', new_slot_path, :class => "btn btn-primary pull-right" %>
  <div class="clearfix"></div>
</div>

app/views/slots/new.html.erb
<div class="col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="purple">
            <h4 class="title">Nuevo Espacio</h4>
        </div>
        <div class="card-content">
        	<%= render 'form', slot: @slot %>
        </div>
    </div>
</div>

<%= link_to 'Volver', slots_path %>

app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="purple">
            <h4 class="title">Ver Espacio</h4>
        </div>
        <div class="card-content">    
            <div class="row">
                <div class="tim-typo">
                    <p>
                        <span class="tim-note">Número</span><%= @slot.number %></p>
                </div>
            </div>
        </div>
        <div class="card-content">    
            <div class="row">
                <div class="tim-typo">
                    <p>
                        <span class="tim-note">Tipo de vehículo</span><%= @slot.vehicle_type.name %></p>
                </div>
            </div>
        </div>
    </div>
</div>

<%= link_to 'Editar', edit_slot_path(@slot) %> |
<%= link_to 'Volver', slots_path %>