config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :reserves
  get '/reserves/exit/:id', :to=>'reserves#exit', :as => :exit_reserve
  get '/reserves/reservePdf/:id', :to=>'reserves#reservePdf', :as => :pdf_reserve

  resources :vehicles
  resources :slots
  resources :vehicle_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reserve.rb
class Reserve < ApplicationRecord
  belongs_to :slot
  belongs_to :vehicle
  accepts_nested_attributes_for :vehicle

  # Función que representa retorna la última reserva de un espacio seleccionado
  def self.reservaActual(id)
  	Reserve.where("slot_id = ?", id).last
  end

  # Función que retorna el cálculo de los minutos de una reserva desde el inicio al final
  def tiempoTranscurrido
  	time = DateTime.now.to_time - self.initTime.to_time
  	minutes = time/60
  	return minutes.round
  end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  before_action :set_reserf, only: [:show, :edit, :update, :destroy, :exit, :reservePdf]

  # GET /reserves
  # GET /reserves.json
  def index
    @reserves = Reserve.all
  end

  # GET /reserves/1
  # GET /reserves/1.json
  def show
  end

  # GET /reserves/new
  def new
    @reserf = Reserve.new
    @slot = Slot.find(params[:format])
    @reserf.slot = @slot
    @reserf.build_vehicle
    @vehicles = Vehicle.all
  end

  # GET /reserves/1/edit
  def edit
  end

  # POST /reserves
  # POST /reserves.json
  def create
    @reserf = Reserve.new(reserf_params)
    @reserf.busy = true

    respond_to do |format|
      if @reserf.save
        format.html { redirect_to root_path, notice: 'Reserve was successfully created.' }
        format.json { render :show, status: :created, location: @reserf }
      else
        format.html { render :new }
        format.json { render json: @reserf.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /reserves/exit/1
  # En esta función se asimila el momento de la salida del vehículo del estacionamiento
  def exit
    @reserf.exitTime = DateTime.now
    @reserf.totalTime = (@reserf.initTime.to_time - @reserf.exitTime.to_time)/60
    @reserf.totalTime = @reserf.totalTime.abs.round
    @reserf.price = (@reserf.totalTime*30)
    @reserf.busy = false

    respond_to do |format|
      if @reserf.save
        format.html 
      else
        format.html { redirect_to root_path}
      end
    end
  end

  # GET /reservas/reservePdf/1
  # En esta función se crea un pdf con el detalle de la reserva al momento de la salida
  def reservePdf
    respond_to do |format|
      format.pdf do
        pdf = TicketPdf.new(@reserf)
        send_data pdf.render, filename: 'ticket.pdf', type: 'application/pdf', :disposition => "inline"
      end
    end
  end

  # PATCH/PUT /reserves/1
  # PATCH/PUT /reserves/1.json
  def update
    respond_to do |format|
      if @reserf.update(reserve_params)
        format.html { redirect_to @reserf, notice: 'Reserve was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserf }
      else
        format.html { render :edit }
        format.json { render json: @reserf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reserves/1
  # DELETE /reserves/1.json
  def destroy
    @reserf.destroy
    respond_to do |format|
      format.html { redirect_to reserves_url, notice: 'Reserve was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserf
      @reserf = Reserve.find(params[:id])
      @vehicle = @reserf.vehicle
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserf_params
      params.require(:reserve).permit(:slot_id, :initTime, vehicle_attributes: [:patente, :vehicle_type_id, :description, :phone])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:patente, :vehicle_type_id, :description, :phone)
    end
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/views/reserves/_form.html.erb
<%= form_for(reserf) do |f| %>
  <% if reserf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reserf.errors.count, "error") %> prohibited this reserf from being saved:</h2>

      <ul>
      <% reserf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :slot_id %>

   <div class="row">
      <div class="col-md-12">
          <div class="form-group label-floating">
              <label class="control-label">Hora de entrada</label>
              <%= f.datetime_select :initTime, :class => "form-control"%>
          </div>
      </div>
  </div>

  <%= f.fields_for(:vehicle) do |ff| %>
    <h4>Vehiculo</h4>

    <div class="row">
      <div class="col-md-12">
          <div class="form-group label-floating">
              <label class="control-label">Patente</label>
              <%= ff.text_field :patente, :class => "form-control"%>
          </div>
      </div>
    </div>    

    <div class="row">
      <div class="col-md-12">
          <div class="form-group label-floating">
              <label class="control-label">Tipo de Vehículo</label>
              <%= ff.select :vehicle_type_id, options_for_select(VehicleType.all.collect {|vehicle_type| [vehicle_type.name, vehicle_type.id ]}, @reserf.vehicle.vehicle_type_id), {}, :class => "form-control", :style =>"width: 100%" %>
          </div>
      </div>
    </div>    

    <div class="row">
      <div class="col-md-12">
          <div class="form-group label-floating">
              <label class="control-label">Descripción</label>
              <%= ff.text_field :description, :class => "form-control"%>
          </div>
      </div>
    </div>    

    <div class="row">
      <div class="col-md-12">
          <div class="form-group label-floating">
              <label class="control-label">Contacto</label>
              <%= ff.text_field :phone, :class => "form-control"%>
          </div>
      </div>
    </div>    

  <% end %>

  <%= f.submit "Crear la Entrada",:class => "btn btn-primary pull-right" %>
  <div class="clearfix"></div>

<% end %>

app/views/reserves/edit.html.erb
<h1>Editing Reserf</h1>

<%= render 'form', reserf: @reserf %>

<%= link_to 'Show', @reserf %> |
<%= link_to 'Back', reserves_path %>

app/views/reserves/exit.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="purple">
            <h4 class="title">Ver Espacio</h4>
        </div>
        <div class="card-content">    
            <div class="row">
                <div class="tim-typo">
                    <p>
                        <span class="tim-note">Número del Espacio</span><%= @reserf.slot.number %></p>
                </div>
            </div>
        </div>
        <div class="card-content">    
            <div class="row">
                <div class="tim-typo">
                    <p>
                        <span class="tim-note">Patente</span><%= @reserf.vehicle.patente %></p>
                </div>
            </div>
        </div>
        <div class="card-content">    
            <div class="row">
                <div class="tim-typo">
                    <p>
                        <span class="tim-note">Hora de Entrada</span><%= @reserf.initTime %></p>
                </div>
            </div>
        </div>
        <div class="card-content">    
            <div class="row">
                <div class="tim-typo">
                    <p>
                        <span class="tim-note">Hora de Salida</span><%= @reserf.exitTime %></p>
                </div>
            </div>
        </div>
        <div class="card-content">    
            <div class="row">
                <div class="tim-typo">
                    <p>
                        <span class="tim-note">Tiempo Total</span><%= @reserf.totalTime %></p>
                </div>
            </div>
        </div>
        <div class="card-content">    
            <div class="row">
                <div class="tim-typo">
                    <p>
                        <span class="tim-note">Precio Total</span>$<%= @reserf.price %></p>
                </div>
            </div>
        </div>

        <%= link_to 'Pantalla Principal', root_path, :class => "btn btn-primary pull-left"%>
        <%= link_to 'Imprimir Ticket', pdf_reserve_path(@reserf, format: 'pdf'), :class => "btn btn-primary pull-right" %>
        
    </div>
</div>

app/views/reserves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reserves</h1>

<table>
  <thead>
    <tr>
      <th>Slot</th>
      <th>Vehicle</th>
      <th>Inittime</th>
      <th>Exittime</th>
      <th>Totaltime</th>
      <th>Price</th>
      <th>Busy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reserves.each do |reserf| %>
      <tr>
        <td><%= reserf.slot %></td>
        <td><%= reserf.vehicle %></td>
        <td><%= reserf.initTime %></td>
        <td><%= reserf.exitTime %></td>
        <td><%= reserf.totalTime %></td>
        <td><%= reserf.price %></td>
        <td><%= reserf.busy %></td>
        <td><%= link_to 'Show', reserf %></td>
        <td><%= link_to 'Edit', edit_reserf_path(reserf) %></td>
        <td><%= link_to 'Destroy', reserf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New reserf', new_reserf_path %>

app/views/reserves/new.html.erb
<div class="col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="purple">
            <h4 class="title">Nueva Reserva de espacio</h4>
            <p class="category">Ingreso de vehículo en el Espacio: <%= @reserf.slot.number %></p>
        </div>
        <div class="card-content">
        	<%= render 'form', reserf: @reserf %>
        </div>
    </div>
</div>

<%= link_to 'Volver', root_path %>

app/views/reserves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Slot:</strong>
  <%= @reserf.slot %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @reserf.vehicle %>
</p>

<p>
  <strong>Inittime:</strong>
  <%= @reserf.initTime %>
</p>

<p>
  <strong>Exittime:</strong>
  <%= @reserf.exitTime %>
</p>

<p>
  <strong>Totaltime:</strong>
  <%= @reserf.totalTime %>
</p>

<p>
  <strong>Price:</strong>
  <%= @reserf.price %>
</p>

<p>
  <strong>Busy:</strong>
  <%= @reserf.busy %>
</p>

<%= link_to 'Edit', edit_reserf_path(@reserf) %> |
<%= link_to 'Back', reserves_path %>