config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :reserves
  get '/reserves/exit/:id', :to=>'reserves#exit', :as => :exit_reserve
  get '/reserves/reservePdf/:id', :to=>'reserves#reservePdf', :as => :pdf_reserve

  resources :vehicles
  resources :slots
  resources :vehicle_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/vehicle_types_controller.rb
class VehicleTypesController < ApplicationController
  before_action :set_vehicle_type, only: [:show, :edit, :update, :destroy]

  # GET /vehicle_types
  # GET /vehicle_types.json
  def index
    @vehicle_types = VehicleType.all
  end

  # GET /vehicle_types/1
  # GET /vehicle_types/1.json
  def show
  end

  # GET /vehicle_types/new
  def new
    @vehicle_type = VehicleType.new
  end

  # GET /vehicle_types/1/edit
  def edit
  end

  # POST /vehicle_types
  # POST /vehicle_types.json
  def create
    @vehicle_type = VehicleType.new(vehicle_type_params)

    respond_to do |format|
      if @vehicle_type.save
        format.html { redirect_to @vehicle_type, notice: 'Vehicle type was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle_type }
      else
        format.html { render :new }
        format.json { render json: @vehicle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_types/1
  # PATCH/PUT /vehicle_types/1.json
  def update
    respond_to do |format|
      if @vehicle_type.update(vehicle_type_params)
        format.html { redirect_to @vehicle_type, notice: 'Vehicle type was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle_type }
      else
        format.html { render :edit }
        format.json { render json: @vehicle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_types/1
  # DELETE /vehicle_types/1.json
  def destroy
    @vehicle_type.destroy
    respond_to do |format|
      format.html { redirect_to vehicle_types_url, notice: 'Vehicle type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_type
      @vehicle_type = VehicleType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_type_params
      params.require(:vehicle_type).permit(:name)
    end
end

app/helpers/vehicle_types_helper.rb
module VehicleTypesHelper
end

app/views/vehicle_types/_form.html.erb
<%= form_for(vehicle_type) do |f| %>
  <% if vehicle_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle_type.errors.count, "error") %> prohibited this vehicle_type from being saved:</h2>

      <ul>
      <% vehicle_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="col-md-12">
          <div class="form-group label-floating">
              <label class="control-label">Nombre del tipo de vehículo</label>
              <%= f.text_field :name, :class => "form-control"%>
          </div>
      </div>
  </div>
  <%= f.submit "Crear Tipo Vehículo",:class => "btn btn-primary pull-right" %>
  <div class="clearfix"></div>
  
  
<% end %>

app/views/vehicle_types/edit.html.erb
<div class="col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="purple">
            <h4 class="title">Editar Tipo de Vehículo</h4>
        </div>
        <div class="card-content">
        	<%= render 'form', vehicle_type: @vehicle_type %>
        </div>
    </div>
</div>


<%= link_to 'Ver', @vehicle_type %> |
<%= link_to 'Volver', vehicle_types_path %>

app/views/vehicle_types/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-12">
  <div class="card">
      <div class="card-header" data-background-color="purple">
          <h4 class="title">Tipos de Vehículos</h4>
          <p class="category">Tabla con todos los tipos de vehículos</p>
      </div>
      <div class="card-content table-responsive">
          <table class="table">
              <thead class="text-primary">
                  <th>Nombre Tipo</th>
                  <th></th>
              </thead>
              <tbody>
                <% @vehicle_types.each do |vehicle_type| %>
                  <tr>
                    <td><%= vehicle_type.name %></td>
                    <td><%= link_to 'Ver', vehicle_type %> |
                    <%= link_to 'Editar', edit_vehicle_type_path(vehicle_type) %> |
                    <%= link_to 'Eliminar', vehicle_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
          </table>
      </div>
  </div>
  
  <%= link_to 'Nuevo Tipo de Vehículo', new_vehicle_type_path, :class => "btn btn-primary pull-right" %>
  <div class="clearfix"></div>
</div>

app/views/vehicle_types/new.html.erb
<div class="col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="purple">
            <h4 class="title">Nuevo tipo de Vehículo</h4>
        </div>
        <div class="card-content">
        	<%= render 'form', vehicle_type: @vehicle_type %>
        </div>
    </div>
</div>

<%= link_to 'Volver', vehicle_types_path %>

app/views/vehicle_types/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="purple">
            <h4 class="title">Ver tipo de Vehículo</h4>
        </div>
        <div class="card-content">    
            <div class="row">
                <div class="tim-typo">
                    <p>
                        <span class="tim-note">Nombre Tipo</span><%= @vehicle_type.name %></p>
                </div>
            </div>
        </div>
    </div>
</div>


<%= link_to 'Editar', edit_vehicle_type_path(@vehicle_type) %> |
<%= link_to 'Volver', vehicle_types_path %>